# Generated by Django 3.2.6 on 2023-06-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='tree',
            new_name='description',
        ),
    ]
