# Generated by Django 3.2.6 on 2023-06-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_rename_tree_tree_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='index',
        ),
    ]
