# Generated by Django 3.2.6 on 2023-06-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_name'),
        ('tree', '0003_remove_tree_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='name',
            field=models.CharField(default='cybersecurity', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.JSONField(null=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
