# Generated by Django 3.2.6 on 2023-06-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20230605_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='name',
            new_name='identifier',
        ),
    ]
