# Generated by Django 3.2.6 on 2023-06-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_rename_name_tree_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=1000)),
                ('label', models.CharField(max_length=1000)),
                ('target', models.CharField(max_length=1000)),
                ('template', models.TextField()),
                ('key', models.TextField()),
                ('heuristics', models.TextField()),
                ('distractors', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_text', models.CharField(max_length=1000)),
                ('field', models.CharField(max_length=1000)),
                ('knowledge_text', models.TextField()),
                ('graph_text', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=1000)),
                ('label', models.CharField(max_length=1000)),
                ('target', models.CharField(max_length=1000)),
                ('key', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=1000)),
                ('level', models.CharField(max_length=1000)),
                ('field', models.CharField(max_length=1000)),
                ('ideation', models.TextField()),
                ('knowledge', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='AnswerSheet',
        ),
    ]
