# Generated by Django 3.2.6 on 2023-06-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0007_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='question',
            name='field',
        ),
    ]
